name: scenario-dreamer
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=24.2

  - pip:
    - hydra-core==1.3.2
    - moviepy==1.0.3
    - wandb==0.18.5
    - tqdm==4.66.5
    - torch==2.2.0
    - matplotlib==3.6.1
    - scipy==1.10.1
    - numpy==1.21.5
    - torch-ema==0.3
    - pytorch-lightning==2.4.0
    - torch_geometric==2.6.1
    - torchaudio==2.2.0
    - tensorflow==2.11.0
    - waymo-open-dataset-tf-2-11-0==1.6.1
    - networkx==3.4.2
    - shapely==2.0.6
    - einops==0.8.0
    - Pillow==9.2.0
    - opencv-python==4.10.0.84